import React from "react";

export default function Fertility() {
    return (
        <div className="fertility">
            <ul>
                <li><span>01</span>Fertility and personal history debrief + planning for next steps, goals, and milestones.
                </li>
                <li><span>02</span>Documentation of each phase of your journey (this can be shared in real time, or time-capsuled until requested).                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fdq
                </li>
                <li><span>03</span>Access to resources including but not limited to: applicable healthcare professionals, fertility awareness, holistic wellness, dietary + lifestyle support, herbalism, relaxation + meditation methods.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                </li>
                <li><span>04</span>Preparation for any/all medical visits (expectations, question to ask). 
                </li>
                <li><span>05</span>Weekly 1-Hour Zoom Meetings                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                </li>
                <li><span>05</span>Preparation for any/all medical visits (expectations, question to ask). 
                </li>
            </ul>
        </div>
    )
}